### ISSUE TITLE
Why cannot generate the CSV

### ISSUE THREAD

**Issue by Luckken21** [DeepRank/DeepRank-GNN-esm#5]
/gpfs/share/home/2200012187/mambaforge/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/torch_geometric/data/collate.py:145: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = elem.storage()._new_shared(numel)
Traceback (most recent call last):
  File "/gpfs/share/home/2200012187/mambaforge/envs/deeprank-gnn-esm-gpu/bin/deeprank-gnn-esm-predict", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2200012187/mambaforge/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 340, in main
    csv_output = predict(input=graph, workspace_path=workspace_path)
  File "/gpfs/share/home/2200012187/mambaforge/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 264, in predict
    output_csv = convert_to_csv(output)
  File "/gpfs/share/home/2200012187/mambaforge/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 274, in convert_to_csv
    assert os.path.exists(csv_path), f"CSV file {csv_path} not found."
AssertionError: CSV file /gpfs/share/home/2200012187/lightdock_workspace/DeepRank-GNN-esm/lightdock_100_82.pdb_design_cdc42_323_dldesign_2_2_af2pred_cleaned-gnn_esm_pred_A_B/GNN_esm_prediction.csv not found.
I successfully run another pdb, but for this , the program cannot generate the csv. Thanks a lot if you can help me

**Comment by ntxxt** [comment]
Hi there,

For this pdb, in the output folder, do you have the generated '/gpfs/share/home/2200012187/lightdock_workspace/DeepRank-GNN-esm/lightdock_100_82.pdb_design_cdc42_323_dldesign_2_2_af2pred_cleaned-gnn_esm_pred_A_B/GNN_esm_prediction.hdf5' file?
 If so, try use 'https://github.com/DeepRank/DeepRank-GNN-esm/blob/main/src/deeprank_gnn/tools/hdf5_to_csv.py' script directly to convert it into hdf5 format;
If not, check the following 1) search for the GNN_esm_prediction.hdf5 file in the output dir, it could be a naming issue 2) check if your input pdb has chain 'A' and 'B' and if the input pdb has been properly cleaned and pre-processed. (should be you use the command-line version of the tool)

If is it still not solved, could you paste all of the output from the cmd tool for this input pdb so that I can have a detailed look? 

Best,
Xiaotong
